'use strict';
const { contextBridge, ipcRenderer } = require('electron');
const call = (ch, ...a) => ipcRenderer.invoke(ch, ...a);
contextBridge.exposeInMainWorld('skapi', {
  getData: () => call('getData'),
  setTier: (n, t) => call('setTier', n, t),
  setUpdatePrompt: (n, t) => call('setUpdatePrompt', n, t),
  useInProject: (n, p, on) => call('useInProject', n, p, on),
  applyLoadout: (lo, p) => call('applyLoadout', lo, p),
  projectInfo: p => call('projectInfo', p),
  recentProjects: () => call('recentProjects'),
  readSkillMd: n => call('readSkillMd', n),
  deleteSkill: n => call('deleteSkill', n),
  createLoadout: (n, m) => call('createLoadout', n, m),
  deleteLoadout: n => call('deleteLoadout', n),
  checkUpdates: () => call('checkUpdates'),
  getConfig: () => call('getConfig'),
  setHubPath: p => call('setHubPath', p),
  cloneHub: (u, d) => call('cloneHub', u, d),
  initHub: d => call('initHub', d),
  getRemote: () => call('getRemote'),
  setRemote: u => call('setRemote', u),
  validateRemote: () => call('validateRemote'),
  gitPull: () => call('gitPull'),
  gitPush: () => call('gitPush'),
  gitSyncStatus: () => call('gitSyncStatus'),
  onHubChanged: cb => ipcRenderer.on('hubChanged', () => cb()),
  pickProject: () => call('pickProject'),
  openRepo: r => call('openRepo', r),
  setTheme: t => call('setTheme', t),
});
